name: 'MigrationPilot'
description: 'Analyze PostgreSQL migrations for safety before deployment'
author: 'Micke Samuel'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  migration-path:
    description: 'Path to migration SQL files'
    required: true
  github-token:
    description: 'GitHub token for PR comments'
    default: ${{ github.token }}
  database-url:
    description: 'PostgreSQL connection string (Pro tier — enables production context)'
    required: false
  license-key:
    description: 'MigrationPilot Pro license key (enables production context + Pro rules)'
    required: false
  pg-version:
    description: 'Target PostgreSQL version'
    default: '17'
  fail-on:
    description: 'Fail CI on: critical, warning, or never'
    default: 'critical'
  exclude:
    description: 'Comma-separated list of rules to skip (e.g. MP001,MP004)'
    required: false
  config-file:
    description: 'Path to .migrationpilotrc.yml config file (auto-detected if not specified)'
    required: false

outputs:
  risk-level:
    description: 'Overall risk level: RED, YELLOW, or GREEN'
  violations:
    description: 'Number of violations found'
  sarif-file:
    description: 'Path to SARIF results file for GitHub Code Scanning'

runs:
  using: 'node22'
  main: 'dist/action/index.js'
