import { describe, it, expect } from 'vitest';
import { buildPRComment } from '../src/output/pr-comment.js';
import type { PRAnalysisResult } from '../src/output/pr-comment.js';

const baseAnalysis: PRAnalysisResult = {
  file: 'migrations/001.sql',
  statements: [{
    sql: 'ALTER TABLE users ADD COLUMN name text;',
    lock: { lockType: 'ACCESS EXCLUSIVE' as const, blocksReads: true, blocksWrites: true, longHeld: false },
    risk: { level: 'RED' as const, score: 80, factors: [] },
  }],
  overallRisk: { level: 'RED' as const, score: 80, factors: [] },
  violations: [],
};

/**
 * This comment gets posted into other people's repositories, so it used to be
 * the most widely seen advertisement in the product: a "Try Pro free for 14
 * days" call to action on every PR without production context. There is no Pro
 * tier. The footer now points at the input that would deepen the analysis.
 */
describe('PR comment footer', () => {
  it('points at --database-url when there is no production context', () => {
    const analysis: PRAnalysisResult = {
      ...baseAnalysis,
      violations: [{
        ruleId: 'MP001',
        ruleName: 'require-concurrent-index',
        severity: 'critical',
        message: 'CREATE INDEX blocks writes.',
        line: 1,
      }],
    };

    const comment = buildPRComment(analysis);
    expect(comment).toContain('database-url');
    expect(comment).toContain('production context');
  });

  it('says the same thing whatever the severity — the hint is not a sales trigger', () => {
    const critical = buildPRComment({
      ...baseAnalysis,
      violations: [{
        ruleId: 'MP001', ruleName: 'require-concurrent-index',
        severity: 'critical', message: 'CREATE INDEX blocks writes.', line: 1,
      }],
    });
    const warning = buildPRComment({
      ...baseAnalysis,
      violations: [{
        ruleId: 'MP004', ruleName: 'require-lock-timeout',
        severity: 'warning', message: 'No lock_timeout set.', line: 1,
      }],
    });
    const clean = buildPRComment(baseAnalysis);

    const footer = (c: string) => c.slice(c.lastIndexOf('<sub>'));
    expect(footer(critical)).toBe(footer(warning));
    expect(footer(warning)).toBe(footer(clean));
  });

  it('drops the hint once production context is present', () => {
    const analysis: PRAnalysisResult = {
      ...baseAnalysis,
      affectedQueries: [{
        normalizedQuery: 'SELECT * FROM users WHERE email = $1',
        calls: 1000,
        meanExecTime: 2.5,
        serviceName: 'api',
      }],
    };

    expect(buildPRComment(analysis)).not.toContain('database-url');
  });

  it('never sells an upgrade, in any of its shapes', () => {
    const shapes = [
      baseAnalysis,
      { ...baseAnalysis, violations: [{ ruleId: 'MP001', ruleName: 'r', severity: 'critical' as const, message: 'm', line: 1 }] },
      { ...baseAnalysis, violations: [{ ruleId: 'MP004', ruleName: 'r', severity: 'warning' as const, message: 'm', line: 1 }] },
      {
        ...baseAnalysis,
        affectedQueries: [{ normalizedQuery: 'SELECT 1', calls: 1, meanExecTime: 1, serviceName: 'api' }],
      },
    ];

    for (const shape of shapes) {
      const comment = buildPRComment(shape);
      expect(comment).not.toMatch(/upgrade to pro/i);
      expect(comment).not.toMatch(/try pro free/i);
      expect(comment).not.toMatch(/migrationpilot\.dev\/pricing/i);
    }
  });

  it('includes MigrationPilot branding in footer', () => {
    const comment = buildPRComment(baseAnalysis);
    expect(comment).toContain('Generated by');
    expect(comment).toContain('migrationpilot.dev');
  });
});
