import { describe, it, expect } from 'vitest';
import { buildPRComment } from '../src/output/pr-comment.js';
import type { PRAnalysisResult } from '../src/output/pr-comment.js';

const baseAnalysis: PRAnalysisResult = {
  file: 'migrations/001.sql',
  statements: [{
    sql: 'ALTER TABLE users ADD COLUMN name text;',
    lock: { lockType: 'ACCESS EXCLUSIVE' as const, blocksReads: true, blocksWrites: true, longHeld: false },
    risk: { level: 'RED' as const, score: 80, factors: [] },
  }],
  overallRisk: { level: 'RED' as const, score: 80, factors: [] },
  violations: [],
};

describe('PR comment upgrade CTA', () => {
  it('shows trial CTA when critical violations and no production context', () => {
    const analysis: PRAnalysisResult = {
      ...baseAnalysis,
      violations: [{
        ruleId: 'MP001',
        ruleName: 'require-concurrent-index',
        severity: 'critical',
        message: 'CREATE INDEX blocks writes.',
        line: 1,
      }],
    };

    const comment = buildPRComment(analysis);
    expect(comment).toContain('Try Pro free for 14 days');
    expect(comment).toContain('migrationpilot.dev/pricing');
  });

  it('shows generic upgrade CTA when only warnings and no production context', () => {
    const analysis: PRAnalysisResult = {
      ...baseAnalysis,
      violations: [{
        ruleId: 'MP004',
        ruleName: 'require-lock-timeout',
        severity: 'warning',
        message: 'No lock_timeout set.',
        line: 1,
      }],
    };

    const comment = buildPRComment(analysis);
    expect(comment).toContain('Upgrade to Pro');
    expect(comment).not.toContain('Try Pro free for 14 days');
  });

  it('shows generic upgrade CTA when no violations and no production context', () => {
    const comment = buildPRComment(baseAnalysis);
    expect(comment).toContain('Upgrade to Pro');
    expect(comment).not.toContain('Try Pro free for 14 days');
  });

  it('does not show upgrade CTA when production context is present', () => {
    const analysis: PRAnalysisResult = {
      ...baseAnalysis,
      affectedQueries: [{
        normalizedQuery: 'SELECT * FROM users WHERE email = $1',
        calls: 1000,
        meanExecTime: 2.5,
        serviceName: 'api',
      }],
    };

    const comment = buildPRComment(analysis);
    expect(comment).not.toContain('Upgrade to Pro');
    expect(comment).not.toContain('Try Pro free for 14 days');
  });

  it('includes MigrationPilot branding in footer', () => {
    const comment = buildPRComment(baseAnalysis);
    expect(comment).toContain('Generated by');
    expect(comment).toContain('migrationpilot.dev');
  });
});
