import type { AnalysisOutput } from './cli.js';
import type { Rule } from '../rules/engine.js';

/**
 * Format analysis output as clean GitHub-Flavored Markdown.
 * No chalk/color dependencies — plain text suitable for docs, wikis, Notion.
 */
export function formatMarkdown(analysis: AnalysisOutput, rules?: Rule[]): string {
  const ruleMap = rules ? new Map(rules.map(r => [r.id, r])) : undefined;
  const lines: string[] = [];
  const criticals = analysis.violations.filter(v => v.severity === 'critical');
  const warnings = analysis.violations.filter(v => v.severity === 'warning');

  lines.push('# Migration Safety Report');
  lines.push('');
  lines.push(`**File**: \`${analysis.file}\`  `);
  lines.push(`**Risk Level**: ${analysis.overallRisk.level} (score: ${analysis.overallRisk.score}/100)  `);

  const parts = [`**Statements**: ${analysis.statements.length}`];
  if (criticals.length > 0) parts.push(`**Critical**: ${criticals.length}`);
  if (warnings.length > 0) parts.push(`**Warnings**: ${warnings.length}`);
  if (criticals.length === 0 && warnings.length === 0) parts.push('**Violations**: 0');
  lines.push(parts.join(' | '));
  lines.push('');

  // DDL Operations table
  if (analysis.statements.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## DDL Operations');
    lines.push('');
    lines.push('| # | Statement | Lock Type | Blocks | Long Held | Risk |');
    lines.push('|---|-----------|-----------|--------|-----------|------|');

    for (let i = 0; i < analysis.statements.length; i++) {
      const s = analysis.statements[i];
      if (!s) continue;
      const sqlPreview = s.sql.replace(/\s+/g, ' ').trim();
      const truncated = sqlPreview.length > 60 ? sqlPreview.slice(0, 57) + '...' : sqlPreview;
      const blocks = s.lock.blocksReads && s.lock.blocksWrites ? 'R+W'
        : s.lock.blocksWrites ? 'Writes'
        : s.lock.blocksReads ? 'Reads'
        : 'None';
      lines.push(`| ${i + 1} | \`${truncated}\` | ${s.lock.lockType} | ${blocks} | ${s.lock.longHeld ? 'Yes' : 'No'} | ${s.risk.level} |`);
    }
    lines.push('');
  }

  // Violations
  if (analysis.violations.length > 0) {
    lines.push('## Violations');
    lines.push('');

    for (const v of analysis.violations) {
      const icon = v.severity === 'critical' ? '🔴' : '🟡';
      lines.push(`### ${icon} ${v.severity.toUpperCase()}: ${v.ruleId} (line ${v.line})`);
      lines.push('');
      lines.push(v.message);
      lines.push('');

      if (ruleMap) {
        const rule = ruleMap.get(v.ruleId);
        if (rule?.whyItMatters) {
          lines.push(`> **Why:** ${rule.whyItMatters}`);
          lines.push('');
        }
        if (rule?.docsUrl) {
          lines.push(`[Documentation](${rule.docsUrl})`);
          lines.push('');
        }
      }

      if (v.safeAlternative) {
        lines.push('**Safe alternative:**');
        lines.push('');
        lines.push('```sql');
        lines.push(v.safeAlternative);
        lines.push('```');
        lines.push('');
      }
    }
  } else {
    lines.push('## Result');
    lines.push('');
    lines.push('✅ No violations found — migration is safe.');
    lines.push('');
  }

  // Risk factors
  if (analysis.overallRisk.factors.length > 0) {
    lines.push('## Risk Factors');
    lines.push('');
    lines.push('| Factor | Score | Detail |');
    lines.push('|--------|------:|--------|');
    for (const f of analysis.overallRisk.factors) {
      lines.push(`| ${f.name} | ${f.value}/${f.weight} | ${f.detail} |`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by [MigrationPilot](https://migrationpilot.dev)*');

  return lines.join('\n');
}
