import type { RiskScore } from '../scoring/score.js';
import type { RuleViolation } from '../rules/engine.js';
import type { LockClassification } from '../locks/classify.js';
import type { AffectedQuery } from '../scoring/score.js';

export interface PRAnalysisResult {
  file: string;
  statements: Array<{
    sql: string;
    lock: LockClassification;
    risk: RiskScore;
  }>;
  overallRisk: RiskScore;
  violations: RuleViolation[];
  affectedQueries?: AffectedQuery[];
}

export function buildPRComment(analysis: PRAnalysisResult): string {
  const emoji = analysis.overallRisk.level === 'RED' ? '🔴'
    : analysis.overallRisk.level === 'YELLOW' ? '🟡' : '🟢';

  const lines: string[] = [];

  // Header
  lines.push(`## ${emoji} MigrationPilot — Migration Safety Report`);
  lines.push('');
  lines.push(`**Risk Level**: **${analysis.overallRisk.level}** (score: ${analysis.overallRisk.score}/100)`);
  lines.push('');

  // DDL Operations table
  if (analysis.statements.length > 0) {
    lines.push('### DDL Operations');
    lines.push('');
    lines.push('| # | Statement | Lock Type | Blocks R/W | Long? | Risk |');
    lines.push('|---|-----------|-----------|:---:|:---:|:---:|');

    for (let i = 0; i < analysis.statements.length; i++) {
      const s = analysis.statements[i];
      const sqlPreview = s.sql.length > 55 ? `\`${s.sql.slice(0, 52)}...\`` : `\`${s.sql}\``;
      const blocksRW = s.lock.blocksReads && s.lock.blocksWrites ? '🔴 R+W'
        : s.lock.blocksWrites ? '🟡 W' : '🟢 —';
      const longHeld = s.lock.longHeld ? '⚠️ Yes' : '✅ No';

      lines.push(`| ${i + 1} | ${sqlPreview} | ${s.lock.lockType} | ${blocksRW} | ${longHeld} | ${riskEmoji(s.risk.level)} |`);
    }

    lines.push('');
  }

  // Violations
  if (analysis.violations.length > 0) {
    lines.push('### Safety Violations');
    lines.push('');

    for (const v of analysis.violations) {
      const icon = v.severity === 'critical' ? '🚨' : '⚠️';
      lines.push(`- ${icon} **${v.severity.toUpperCase()}** [\`${v.ruleId}\`]: ${v.message}`);
    }

    lines.push('');

    // Safe alternatives (show first one with an alternative)
    const withAlt = analysis.violations.find(v => v.safeAlternative);
    if (withAlt) {
      lines.push('<details>');
      lines.push(`<summary>💡 Suggested safe alternative for ${withAlt.ruleId}</summary>`);
      lines.push('');
      lines.push('```sql');
      lines.push(withAlt.safeAlternative!);
      lines.push('```');
      lines.push('</details>');
      lines.push('');
    }
  }

  // Affected queries (paid tier)
  if (analysis.affectedQueries && analysis.affectedQueries.length > 0) {
    lines.push('### Affected Queries (from pg_stat_statements)');
    lines.push('');
    lines.push('| Query | Calls/hr | Avg Time | Service |');
    lines.push('|-------|----------|----------|---------|');

    for (const q of analysis.affectedQueries.slice(0, 10)) {
      const queryPreview = q.normalizedQuery.length > 45
        ? `\`${q.normalizedQuery.slice(0, 42)}...\``
        : `\`${q.normalizedQuery}\``;
      lines.push(`| ${queryPreview} | ${q.calls.toLocaleString()} | ${q.meanExecTime.toFixed(1)}ms | ${q.serviceName ?? 'unknown'} |`);
    }

    if (analysis.affectedQueries.length > 10) {
      lines.push(`| ... and ${analysis.affectedQueries.length - 10} more | | | |`);
    }

    lines.push('');
  }

  // Risk factors
  if (analysis.overallRisk.factors.length > 0) {
    lines.push('<details>');
    lines.push('<summary>📊 Risk Score Breakdown</summary>');
    lines.push('');
    lines.push('| Factor | Score | Detail |');
    lines.push('|--------|:-----:|--------|');
    for (const f of analysis.overallRisk.factors) {
      lines.push(`| ${f.name} | ${f.value}/${f.weight} | ${f.detail} |`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  // Footer with upgrade CTA
  lines.push('---');
  lines.push('<sub>Generated by <a href="https://migrationpilot.dev">MigrationPilot</a>');

  if (!analysis.affectedQueries) {
    lines.push(' · <a href="https://migrationpilot.dev/pricing">Upgrade to Pro</a> for production context: table sizes, affected queries, service dependencies');
  }

  lines.push('</sub>');

  return lines.join('\n');
}

function riskEmoji(level: string): string {
  switch (level) {
    case 'RED': return '🔴';
    case 'YELLOW': return '🟡';
    case 'GREEN': return '🟢';
    default: return '⚪';
  }
}
