import { CaretDown } from '@phosphor-icons/react/ssr';
import { Sql } from '@/components/sql';

/*
 * What the GitHub Action posts on a pull request.
 *
 * Every value here comes from running buildPRComment (src/output/pr-comment.ts)
 * over migrations/003_orders_amount_check.sql with the shipped engine. The
 * structure mirrors the markdown the formatter emits, rendered the way GitHub
 * renders it, so this is the surface a reviewer actually sees rather than a
 * screenshot of one.
 *
 * The coloured circles are the formatter's own emoji, quoted, not iconography
 * chosen for this page.
 */

const SAFE_ALTERNATIVE = `-- Set a timeout so DDL fails fast instead of blocking the queue
SET lock_timeout = '5s';
ALTER TABLE orders
  ADD CONSTRAINT orders_amount_positive CHECK (amount > 0)
RESET lock_timeout;`;

const VIOLATIONS = [
  {
    id: 'MP004',
    message:
      'DDL statement acquires ACCESS EXCLUSIVE lock without a preceding SET lock_timeout. Without a timeout, this statement could block the lock queue indefinitely if it can’t acquire the lock, causing cascading query failures.',
  },
  {
    id: 'MP030',
    message:
      'CHECK constraint "orders_amount_positive" on "orders" without NOT VALID scans the entire table under ACCESS EXCLUSIVE lock, blocking all reads and writes.',
  },
];

export function PrComment() {
  return (
    <div className="overflow-hidden rounded-xl border border-line bg-surface">
      <div className="flex items-center gap-2 border-b border-line-soft px-4 py-2.5">
        <span className="font-mono text-xs text-fg">github-actions</span>
        <span className="rounded border border-line px-1.5 py-0.5 font-mono text-[10px] text-faint">
          bot
        </span>
        <span className="font-mono text-xs text-faint">commented on migrations/</span>
      </div>

      <div className="space-y-4 px-4 py-4 text-[13px] leading-relaxed">
        <p className="text-[15px] font-semibold text-fg">
          <span aria-hidden>&#128308;</span> MigrationPilot: Migration Safety Report
        </p>

        <p className="text-muted">
          <span className="font-semibold text-fg">Risk Level</span>:{' '}
          <span className="font-semibold text-danger">RED</span> (score: 80/100)
        </p>

        <div>
          <p className="mb-2 font-semibold text-fg">DDL Operations</p>
          <div className="mp-scroll overflow-x-auto rounded-lg border border-line-soft">
            <table className="w-full min-w-[520px] border-collapse text-left font-mono text-xs">
              <thead>
                <tr className="border-b border-line-soft text-faint">
                  <th className="px-3 py-2 font-normal">#</th>
                  <th className="px-3 py-2 font-normal">Statement</th>
                  <th className="px-3 py-2 font-normal">Lock Type</th>
                  <th className="px-3 py-2 font-normal">Blocks R/W</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="px-3 py-2 text-faint">1</td>
                  <td className="whitespace-nowrap px-3 py-2 text-fg">
                    ALTER TABLE orders ADD CONSTRAINT orders_amount_posi...
                  </td>
                  <td className="whitespace-nowrap px-3 py-2 text-danger">ACCESS EXCLUSIVE</td>
                  <td className="px-3 py-2 text-danger">R+W</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div>
          <p className="mb-2 font-semibold text-fg">Safety Violations</p>
          <ul className="space-y-2">
            {VIOLATIONS.map((v) => (
              <li key={v.id} className="flex gap-2 text-muted">
                <span aria-hidden className="shrink-0 text-danger">
                  &#8226;
                </span>
                <span>
                  <span className="font-semibold text-danger">CRITICAL</span>{' '}
                  <code className="font-mono text-xs text-fg">[{v.id}]</code>: {v.message}
                </span>
              </li>
            ))}
          </ul>
        </div>

        <div className="rounded-lg border border-line-soft">
          <p className="flex items-center gap-2 px-3 py-2 text-muted">
            <CaretDown size={12} weight="bold" className="text-faint" />
            Suggested safe alternative for MP004
          </p>
          <pre className="mp-scroll overflow-x-auto border-t border-line-soft px-3 py-2.5 font-mono text-xs leading-[1.7]">
            <Sql code={SAFE_ALTERNATIVE} />
          </pre>
        </div>

        <p className="border-t border-line-soft pt-3 text-[11px] text-faint">
          Generated by MigrationPilot. Pass <code className="font-mono">database-url</code> to add
          production context: table sizes, affected queries, replication state.
        </p>
      </div>
    </div>
  );
}
