/**
 * Generates the evidence each rule page carries, from the repo itself:
 *
 *  1. cliFindingByRuleId — the finding the CLI actually prints for the rule's
 *     own flagged example, taken verbatim out of `formatCliOutput`. Writing
 *     these by hand is how a page ends up quoting output the tool stopped
 *     producing three releases ago.
 *  2. relatedRulesByRuleId — the "Related Rules" section of each rule's doc.
 *
 * Handbook citations are not here: each chapter's front matter already names the
 * rules it covers, so the rule pages read that mapping straight from
 * site/src/lib/handbook.ts.
 *
 * The examples themselves are checked by verify-rule-examples.ts, and both
 * scripts read the same production fixtures, so a rule whose example changes
 * gets a new sample output and a fresh pass through the gate together.
 *
 *   npx tsx scripts/generate-rule-evidence.ts
 *
 * Writes site/src/app/rule-evidence.ts. Commit the result.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { analyzeSQL } from '../src/analysis/analyze.js';
import { allRules } from '../src/rules/index.js';
import { formatCliOutput } from '../src/output/cli.js';
import { rules } from '../site/src/app/rule-data.js';
import { PG_VERSION, contexts, pgVersions } from './rule-fixtures.js';

const RULE_DOC_DIR = 'docs/rules';
const OUT = 'site/src/app/rule-evidence.ts';

const stripAnsi = (s: string) => s.replace(/\u001b\[[0-9;]*m/g, '');

/**
 * The docs are checked in with CRLF. JavaScript's `.` does not match `\r`, so a
 * line-anchored pattern silently fails on every one of them — read through this.
 */
const readText = (path: string) => readFileSync(path, 'utf8').replace(/\r\n/g, '\n');

/**
 * Pull this rule's own violation block out of the full report. The CLI prints
 * every rule that fires on the example — MP001's index also trips MP004, MP020
 * and MP023 — and stacking all of them on one rule's page teaches the wrong
 * thing. The bytes are unedited; only the other rules' blocks are dropped.
 */
function extractFinding(report: string, ruleId: string): string | null {
  const lines = report.split('\n');
  const start = lines.findIndex((l) => l.includes(`[${ruleId}]`) && /^\s*[✗⚠]/.test(l));
  if (start === -1) return null;

  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*[✗⚠]\s*\[MP\d+\]/.test(line) || /^\s{2}\S/.test(line)) {
      end = i;
      break;
    }
  }

  return lines
    .slice(start, end)
    .join('\n')
    .replace(/\s+$/, '')
    // The stanza is indented two spaces inside the report; on the page it is
    // the whole code block, so the common indent is noise.
    .replace(/^ {2}/gm, '');
}

const findings: Record<string, string> = {};
const parseFailures: string[] = [];

for (const rule of rules) {
  const pgVersion = pgVersions[rule.id] ?? PG_VERSION;
  try {
    const report = await analyzeSQL(
      rule.badExample,
      'migration.sql',
      pgVersion,
      allRules,
      contexts[rule.id],
    );
    const finding = extractFinding(stripAnsi(formatCliOutput(report, { rules: allRules })), rule.id);
    if (finding) findings[rule.id] = finding;
    else parseFailures.push(`${rule.id} (analysed, but did not fire)`);
  } catch (e) {
    parseFailures.push(`${rule.id} (${(e as Error).message.slice(0, 60)})`);
  }
}

// ── related rules, from each rule's own doc ──────────────────────────────────

const related: Record<string, { id: string; name: string; note: string }[]> = {};
const knownIds = new Set(rules.map((r) => r.id));

for (const rule of rules) {
  let doc: string;
  try {
    doc = readText(join(RULE_DOC_DIR, `${rule.id}.md`));
  } catch {
    continue;
  }
  const section = doc.split(/^##\s+Related Rules\s*$/m)[1];
  if (!section) continue;

  const siblings = section
    .split(/^##\s/m)[0]
    .split('\n')
    .map((line) => line.match(/^-\s*\[(MP\d+)\]\([^)]*\)\s*(\S+)?\s*(?:--|—)?\s*(.*)$/))
    .filter((m): m is RegExpMatchArray => !!m && knownIds.has(m[1]))
    .map((m) => ({ id: m[1], name: m[2] ?? '', note: m[3].trim() }));

  if (siblings.length > 0) related[rule.id] = siblings;
}

// ── emit ─────────────────────────────────────────────────────────────────────

const q = (s: string) => JSON.stringify(s);

const file = `// Generated by scripts/generate-rule-evidence.ts — do not edit by hand.
//
// The CLI findings are the real output of \`formatCliOutput\` over each rule's
// flagged example, with the other rules' blocks removed. Related rules come from
// docs/rules/*.md. Regenerate after changing an example, a rule message, or a doc:
//
//   npx tsx scripts/generate-rule-evidence.ts

/** What the CLI prints for this rule, on this rule's own flagged example. */
export const cliFindingByRuleId: Record<string, string> = {
${Object.entries(findings)
  .map(([id, text]) => `  ${id}: ${q(text)},`)
  .join('\n')}
};

/** The "Related Rules" section of each rule's doc. */
export const relatedRulesByRuleId: Record<string, { id: string; name: string; note: string }[]> = {
${Object.entries(related)
  .map(
    ([id, ss]) =>
      `  ${id}: [\n${ss
        .map((s) => `    { id: ${q(s.id)}, name: ${q(s.name)}, note: ${q(s.note)} },`)
        .join('\n')}\n  ],`,
  )
  .join('\n')}
};
`;

writeFileSync(OUT, file);

console.log(`${OUT}`);
console.log(`  cli findings     ${Object.keys(findings).length}/${rules.length}`);
console.log(`  related rules    ${Object.keys(related).length} rules`);
if (parseFailures.length > 0) {
  console.log(`  no finding for   ${parseFailures.join(', ')}`);
}
