/**
 * Auto-fix engine for MigrationPilot.
 *
 * Rewrites unsafe SQL into safe SQL for rules whose fix is mechanical: a
 * deterministic, semantics-preserving edit to one statement (or to the
 * transaction wrapper around it). Anything that needs several coordinated
 * statements belongs to `migrationpilot plan-fix`; anything that needs a
 * decision belongs to a human. See `classification.ts` for the full table.
 *
 * Mechanical fixes:
 * - MP001  CREATE INDEX            → CREATE INDEX CONCURRENTLY
 * - MP004  (prepend)               → SET lock_timeout = '5s'
 * - MP005  ADD CONSTRAINT ... FK   → ... NOT VALID
 * - MP009  DROP INDEX              → DROP INDEX CONCURRENTLY
 * - MP012  ALTER TYPE ADD VALUE    → lifted out of BEGIN/COMMIT
 * - MP020  (prepend)               → SET statement_timeout = '30s'
 * - MP021  REINDEX                 → REINDEX CONCURRENTLY
 * - MP023  CREATE TABLE/INDEX      → ... IF NOT EXISTS
 * - MP025  CONCURRENTLY in tx      → lifted out of BEGIN/COMMIT
 * - MP030  ADD CONSTRAINT CHECK    → ... NOT VALID
 * - MP033  REFRESH MATVIEW         → REFRESH MATERIALIZED VIEW CONCURRENTLY
 * - MP037  VARCHAR(n)              → TEXT
 * - MP038  INT pk/fk in CREATE     → BIGINT
 * - MP039  SERIAL in CREATE        → GENERATED BY DEFAULT AS IDENTITY
 * - MP040  TIMESTAMP               → TIMESTAMPTZ
 * - MP041  CHAR(n)                 → TEXT
 * - MP042  unnamed CREATE INDEX    → explicit table_col_idx name
 * - MP046  DETACH PARTITION        → DETACH PARTITION CONCURRENTLY
 * - MP074  ADD CONSTRAINT ... FK   → ... DEFERRABLE INITIALLY IMMEDIATE
 * - MP077  pglz                    → lz4
 */

import type { RuleViolation } from '../rules/engine.js';
import { MECHANICAL_RULE_IDS, PLAN_ONLY_RULE_IDS } from './classification.js';
import { splitStatements } from './statements.js';
import type { SqlStatementSpan } from './statements.js';
import { stripLeadingComments } from '../analysis/transaction.js';

export interface FixResult {
  /** The fixed SQL output */
  fixedSql: string;
  /** Number of violations that were auto-fixed */
  fixedCount: number;
  /** Violations that could not be auto-fixed (require manual intervention) */
  unfixable: RuleViolation[];
  /** Unfixed violations whose safe fix is a choreography — see `plan-fix` */
  planOnly: RuleViolation[];
}

/**
 * Order in which fixes are applied to a single statement.
 *
 * Only two pairs actually interact, but both matter:
 * MP042 names an index before MP001/MP023 insert keywords in front of `ON`,
 * and MP074's `DEFERRABLE` must land before MP005 appends the trailing
 * `NOT VALID` that PostgreSQL's grammar requires to come last.
 */
const FIX_ORDER = [
  'MP042', 'MP001', 'MP009', 'MP021', 'MP033', 'MP046', 'MP023',
  'MP037', 'MP038', 'MP039', 'MP040', 'MP041', 'MP077',
  'MP074', 'MP005', 'MP030',
];

/** Rewrites that act on one statement's text. `null` means "not applicable". */
const STATEMENT_FIXES: Record<string, (text: string) => string | null> = {
  MP001: fixMP001,
  MP005: fixMP005,
  MP009: fixMP009,
  MP021: fixMP021,
  MP023: fixMP023,
  MP030: fixMP030,
  MP033: fixMP033,
  MP037: fixMP037,
  MP038: fixMP038,
  MP039: fixMP039,
  MP040: fixMP040,
  MP041: fixMP041,
  MP042: fixMP042,
  MP046: fixMP046,
  MP074: fixMP074,
  MP077: fixMP077,
};

/** Rules fixed by lifting the statement out of its transaction block. */
const TRANSACTION_FIXES = new Set(['MP012', 'MP025']);

/** One statement plus the edits queued against it. */
interface Piece {
  span: SqlStatementSpan;
  /** Whitespace and comments between the previous statement and this one */
  gapBefore: string;
  /** Statement text after rewrites; empty once the statement is removed */
  text: string;
  /** Lines inserted immediately before the statement */
  prepends: string[];
  removed: boolean;
}

/**
 * Auto-fix a SQL migration by replacing unsafe statements with safe alternatives.
 * Returns the fixed SQL, the violations that were fixed, and everything left over.
 */
export function autoFix(sql: string, violations: RuleViolation[]): FixResult {
  const unfixable: RuleViolation[] = [];
  const planOnly: RuleViolation[] = [];
  const candidates: RuleViolation[] = [];

  for (const v of violations) {
    if (MECHANICAL_RULE_IDS.has(v.ruleId)) candidates.push(v);
    else if (PLAN_ONLY_RULE_IDS.has(v.ruleId)) {
      planOnly.push(v);
      unfixable.push(v);
    } else unfixable.push(v);
  }

  if (candidates.length === 0) {
    return { fixedSql: sql, fixedCount: 0, unfixable, planOnly };
  }

  const spans = splitStatements(sql);
  if (spans.length === 0) {
    return { fixedSql: sql, fixedCount: 0, unfixable: violations.slice(), planOnly };
  }

  const pieces = buildPieces(sql, spans);
  const trailingGap = sql.slice(spans[spans.length - 1]!.end);

  // Timeout guards are per-file, not per-statement: one SET covers the
  // statements that follow it, so track whether the file already has one.
  let hasLockTimeout = false;
  let hasStatementTimeout = false;

  const assign = assigner(pieces);
  let fixedCount = 0;

  const ordered = [...candidates].sort(
    (a, b) => a.line - b.line || fixRank(a.ruleId) - fixRank(b.ruleId),
  );

  for (const v of ordered) {
    const piece = assign(v);
    if (!piece || piece.removed) {
      unfixable.push(v);
      continue;
    }

    // Anything before this statement that already sets a timeout counts.
    const preceding = sql.slice(0, piece.span.start).toLowerCase();
    if (!hasLockTimeout && preceding.includes('lock_timeout')) hasLockTimeout = true;
    if (!hasStatementTimeout && preceding.includes('statement_timeout')) hasStatementTimeout = true;

    if (v.ruleId === 'MP004') {
      if (!hasLockTimeout) {
        piece.prepends.push("SET lock_timeout = '5s';");
        hasLockTimeout = true;
      }
      fixedCount++;
      continue;
    }

    if (v.ruleId === 'MP020') {
      if (!hasStatementTimeout) {
        piece.prepends.push("SET statement_timeout = '30s';");
        hasStatementTimeout = true;
      }
      fixedCount++;
      continue;
    }

    if (TRANSACTION_FIXES.has(v.ruleId)) {
      if (liftOutOfTransaction(pieces, piece)) fixedCount++;
      else unfixable.push(v);
      continue;
    }

    const fix = STATEMENT_FIXES[v.ruleId];
    const next = fix?.(piece.text) ?? null;
    if (next === null || next === piece.text) {
      unfixable.push(v);
      continue;
    }
    piece.text = next;
    fixedCount++;
  }

  return {
    fixedSql: render(pieces, trailingGap),
    fixedCount,
    unfixable,
    planOnly,
  };
}

/**
 * Check if a rule is auto-fixable.
 */
export function isFixable(ruleId: string): boolean {
  return MECHANICAL_RULE_IDS.has(ruleId);
}

/** Number of rules `--fix` can rewrite. */
export const FIXABLE_RULE_COUNT = MECHANICAL_RULE_IDS.size;

/** Rule IDs `--fix` can rewrite, sorted. */
export function fixableRuleIds(): string[] {
  return [...MECHANICAL_RULE_IDS].sort();
}

function fixRank(ruleId: string): number {
  const i = FIX_ORDER.indexOf(ruleId);
  return i === -1 ? FIX_ORDER.length : i;
}

function buildPieces(sql: string, spans: SqlStatementSpan[]): Piece[] {
  return spans.map((span, i) => ({
    span,
    gapBefore: sql.slice(i === 0 ? 0 : spans[i - 1]!.end, span.start),
    text: span.text,
    prepends: [],
    removed: false,
  }));
}

/**
 * Does this rule's fix have anything to do on this statement?
 *
 * Used to break ties, so a violation never lands on a neighbouring statement
 * that the rule could not have fired on.
 */
function applies(ruleId: string, text: string): boolean {
  const fix = STATEMENT_FIXES[ruleId];
  if (fix) return fix(text) !== null;
  if (ruleId === 'MP012') return /ALTER\s+TYPE\b[\s\S]*\bADD\s+VALUE\b/i.test(text);
  if (ruleId === 'MP025') return /\bCONCURRENTLY\b/i.test(text);
  // MP004 and MP020 skip session settings, transaction control, and CREATE
  // TABLE (a brand-new table has nothing to contend with), so a violation
  // never belongs to one of those.
  if (ruleId === 'MP004' || ruleId === 'MP020') {
    return !/^\s*(SET|RESET|SHOW|BEGIN|START|COMMIT|END|ROLLBACK|SAVEPOINT|RELEASE)\b/i.test(text)
      && !/^\s*CREATE\s+(?:GLOBAL\s+|LOCAL\s+)?(?:TEMP(?:ORARY)?\s+|UNLOGGED\s+)?TABLE\b/i.test(text);
  }
  return true;
}

/**
 * Match a violation to the statement it belongs to.
 *
 * `reportedLine` is the primary key because that is the line rules actually
 * emit. Several statements can share one — `A; B;` on a single line, or a
 * statement separated from its predecessor by blank lines — so ties are broken
 * first by whether the fix has anything to do on that statement, then by
 * arrival order, which keeps `CREATE INDEX a; CREATE INDEX b;` from fixing the
 * first index twice.
 */
function assigner(pieces: Piece[]): (v: RuleViolation) => Piece | undefined {
  const used = new Map<string, Set<Piece>>();

  return (v: RuleViolation) => {
    let pool = pieces.filter(p => p.span.reportedLine === v.line);
    if (pool.length === 0) pool = pieces.filter(p => p.span.startLine === v.line);
    if (pool.length === 0) {
      pool = pieces.filter(p => p.span.startLine <= v.line && v.line <= p.span.endLine);
    }
    if (pool.length === 0) return undefined;

    const taken = used.get(v.ruleId) ?? new Set<Piece>();
    used.set(v.ruleId, taken);

    const pick =
      pool.find(p => !taken.has(p) && applies(v.ruleId, p.text))
      ?? pool.find(p => !taken.has(p))
      ?? pool[pool.length - 1]!;

    taken.add(pick);
    return pick;
  };
}

function render(pieces: Piece[], trailingGap: string): string {
  const out: string[] = [];
  for (const piece of pieces) {
    if (piece.removed) continue;
    out.push(piece.gapBefore);
    for (const line of piece.prepends) {
      out.push(line, '\n', lineIndentOf(piece));
    }
    out.push(piece.text);
  }
  out.push(trailingGap);
  return out.join('');
}

function lineIndentOf(piece: Piece): string {
  const match = /(?:^|\n)([ \t]*)$/.exec(piece.gapBefore);
  return match?.[1] ?? '';
}

/**
 * Move a statement outside its BEGIN/COMMIT block.
 *
 * Only the unambiguous positions are handled — first, last, or only statement
 * in the block — because those keep every statement in its original order.
 * A statement in the middle would have to split the block in two, changing
 * which statements are atomic with which, so it is left for a human.
 */
function liftOutOfTransaction(pieces: Piece[], target: Piece): boolean {
  const live = pieces.filter(p => !p.removed);
  const at = live.indexOf(target);
  if (at === -1) return false;

  let beginAt = -1;
  for (let i = at - 1; i >= 0; i--) {
    const kind = txKind(live[i]!.text);
    if (kind === 'begin') { beginAt = i; break; }
    if (kind === 'commit') return false;
  }
  if (beginAt === -1) return false;

  let commitAt = -1;
  for (let i = at + 1; i < live.length; i++) {
    const kind = txKind(live[i]!.text);
    if (kind === 'commit') { commitAt = i; break; }
    if (kind === 'begin') return false;
  }
  if (commitAt === -1) return false;

  const members = commitAt - beginAt - 1;
  const isFirst = at === beginAt + 1;
  const isLast = at === commitAt - 1;

  if (members === 1) {
    // The block wraps nothing else — a lone statement is already atomic.
    remove(pieces, live[beginAt]!);
    remove(pieces, live[commitAt]!);
    return true;
  }

  if (isFirst) {
    // BEGIN moves down to just after the lifted statement.
    const begin = live[beginAt]!;
    const nextMember = live[at + 1]!;
    nextMember.prepends.unshift(statementLine(begin.text));
    remove(pieces, begin);
    return true;
  }

  if (isLast) {
    // COMMIT moves up to just before the lifted statement.
    const commit = live[commitAt]!;
    target.prepends.unshift(statementLine(commit.text));
    remove(pieces, commit);
    return true;
  }

  return false;
}

function remove(pieces: Piece[], piece: Piece): void {
  const i = pieces.indexOf(piece);
  const next = pieces.slice(i + 1).find(p => !p.removed);
  if (next) next.gapBefore = piece.gapBefore;
  piece.removed = true;
}

/** Normalise a statement into a single line ending in `;`. */
function statementLine(text: string): string {
  const trimmed = text.trim();
  return trimmed.endsWith(';') ? trimmed : `${trimmed};`;
}

function txKind(text: string): 'begin' | 'commit' | null {
  // Strip any comment above the keyword: the parser hands a statement its
  // preceding comment, so `-- step 1\nBEGIN;` must still read as a BEGIN.
  const head = stripLeadingComments(text).trim().toLowerCase().replace(/;\s*$/, '');
  if (/^(begin|start\s+transaction)(\s|$)/.test(head)) return 'begin';
  if (/^(commit|end|rollback)(\s|$)/.test(head)) return 'commit';
  return null;
}

/**
 * Append a clause just before the terminating semicolon.
 * `NOT VALID` must stay last in PostgreSQL's constraint grammar, so anything
 * appended later slots in front of it.
 */
function appendClause(text: string, clause: string, beforeNotValid: boolean): string {
  const notValid = /\s+NOT\s+VALID\s*(;?)\s*$/i.exec(text);
  if (beforeNotValid && notValid) {
    return text.slice(0, notValid.index) + ` ${clause}` + text.slice(notValid.index);
  }
  if (/;\s*$/.test(text)) return text.replace(/\s*;\s*$/, ` ${clause};`);
  return `${text.trimEnd()} ${clause}`;
}

/**
 * MP001: CREATE INDEX → CREATE INDEX CONCURRENTLY
 * Handles both "CREATE INDEX" and "CREATE UNIQUE INDEX".
 */
function fixMP001(text: string): string | null {
  if (/create\s+(unique\s+)?index\s+concurrently/i.test(text)) return null;
  if (!/CREATE\s+(UNIQUE\s+)?INDEX\s/i.test(text)) return null;

  return text.replace(
    /CREATE\s+(UNIQUE\s+)?INDEX\s+/i,
    (_m, unique: string | undefined) => `CREATE ${unique ? 'UNIQUE ' : ''}INDEX CONCURRENTLY `,
  );
}

/**
 * MP005: ADD CONSTRAINT ... FOREIGN KEY → ... NOT VALID
 * Skips the scan of existing rows; validate it afterwards with plan-fix.
 */
function fixMP005(text: string): string | null {
  if (/not\s+valid\s*;?\s*$/i.test(text)) return null;
  if (!/ADD\s+CONSTRAINT/i.test(text) || !/FOREIGN\s+KEY/i.test(text)) return null;
  return appendClause(text, 'NOT VALID', false);
}

/**
 * MP009: DROP INDEX → DROP INDEX CONCURRENTLY
 */
function fixMP009(text: string): string | null {
  if (/drop\s+index\s+concurrently/i.test(text)) return null;
  if (!/DROP\s+INDEX\s/i.test(text)) return null;

  if (/DROP\s+INDEX\s+IF\s+EXISTS\s+/i.test(text)) {
    return text.replace(/DROP\s+INDEX\s+IF\s+EXISTS\s+/i, 'DROP INDEX CONCURRENTLY IF EXISTS ');
  }
  return text.replace(/DROP\s+INDEX\s+/i, 'DROP INDEX CONCURRENTLY ');
}

/**
 * MP030: ADD CONSTRAINT CHECK → ADD CONSTRAINT CHECK ... NOT VALID
 */
function fixMP030(text: string): string | null {
  if (/not\s+valid\s*;?\s*$/i.test(text)) return null;
  return appendClause(text, 'NOT VALID', false);
}

/**
 * MP021: REINDEX → REINDEX CONCURRENTLY
 * Handles REINDEX TABLE, REINDEX INDEX, REINDEX SCHEMA, REINDEX DATABASE.
 */
function fixMP021(text: string): string | null {
  if (/concurrently/i.test(text)) return null;
  if (!/REINDEX\s+(TABLE|INDEX|SCHEMA|DATABASE)\s/i.test(text)) return null;
  return text.replace(/REINDEX\s+(TABLE|INDEX|SCHEMA|DATABASE)\s+/i, 'REINDEX $1 CONCURRENTLY ');
}

/**
 * MP023: CREATE TABLE/INDEX → CREATE TABLE/INDEX IF NOT EXISTS
 * Handles CREATE TABLE, CREATE INDEX, CREATE UNIQUE INDEX, and CONCURRENTLY variants.
 */
function fixMP023(text: string): string | null {
  if (/if\s+not\s+exists/i.test(text)) return null;

  const index = /CREATE\s+(UNIQUE\s+)?INDEX\s+(CONCURRENTLY\s+)?/i;
  if (index.test(text)) {
    // PostgreSQL's grammar is `INDEX [CONCURRENTLY] [[IF NOT EXISTS] name]` —
    // the clause needs a name to attach to. MP042 supplies one first when it
    // can; when it cannot, adding IF NOT EXISTS here would produce a syntax
    // error, so leave the statement alone.
    if (/CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?ON\s/i.test(text)) return null;
    return text.replace(index, (_m, unique: string | undefined, concurrent: string | undefined) =>
      `CREATE ${unique ? 'UNIQUE ' : ''}INDEX ${concurrent ? 'CONCURRENTLY ' : ''}IF NOT EXISTS `);
  }
  if (/CREATE\s+TABLE\s/i.test(text)) {
    return text.replace(/CREATE\s+TABLE\s+/i, 'CREATE TABLE IF NOT EXISTS ');
  }
  return null;
}

/**
 * MP033: REFRESH MATERIALIZED VIEW → REFRESH MATERIALIZED VIEW CONCURRENTLY
 */
function fixMP033(text: string): string | null {
  if (/concurrently/i.test(text)) return null;
  if (!/REFRESH\s+MATERIALIZED\s+VIEW\s/i.test(text)) return null;
  return text.replace(/REFRESH\s+MATERIALIZED\s+VIEW\s+/i, 'REFRESH MATERIALIZED VIEW CONCURRENTLY ');
}

/**
 * MP037: VARCHAR(n) → TEXT
 * Replaces VARCHAR(n) and CHARACTER VARYING(n) with TEXT.
 */
function fixMP037(text: string): string | null {
  const next = text
    .replace(/CHARACTER\s+VARYING\s*\(\s*\d+\s*\)/gi, 'TEXT')
    .replace(/VARCHAR\s*\(\s*\d+\s*\)/gi, 'TEXT');
  return next === text ? null : next;
}

/**
 * MP040: TIMESTAMP → TIMESTAMPTZ
 *
 * Handles the fractional-seconds form too: Rails and friends emit
 * `timestamp(6) without time zone`, and rewriting only the leading keyword
 * would leave `TIMESTAMPTZ(6) without time zone`, which does not parse.
 * `TIMESTAMP WITH TIME ZONE` is already timestamptz, so it is left as written,
 * and `\b` keeps `current_timestamp` out of it.
 */
function fixMP040(text: string): string | null {
  const next = text.replace(
    /\bTIMESTAMP\b(\s*\(\s*\d+\s*\))?(\s+WITH(?:OUT)?\s+TIME\s+ZONE)?/gi,
    (match: string, precision: string | undefined, zone: string | undefined) => {
      if (zone && !/WITHOUT/i.test(zone)) return match;
      return `TIMESTAMPTZ${precision ?? ''}`;
    },
  );
  return next === text ? null : next;
}

/**
 * MP041: CHAR(n) → TEXT
 * Replaces CHAR(n) and CHARACTER(n) with TEXT. Does not touch VARCHAR.
 */
function fixMP041(text: string): string | null {
  const next = text
    .replace(/CHARACTER\s*\(\s*\d+\s*\)(?!\s+VARYING)/gi, 'TEXT')
    .replace(/\bCHAR\s*\(\s*\d+\s*\)/gi, 'TEXT');
  return next === text ? null : next;
}

/**
 * MP046: DETACH PARTITION → DETACH PARTITION CONCURRENTLY
 */
function fixMP046(text: string): string | null {
  if (/concurrently/i.test(text)) return null;
  if (!/DETACH\s+PARTITION\s/i.test(text)) return null;
  return text.replace(/DETACH\s+PARTITION\s+/i, 'DETACH PARTITION CONCURRENTLY ');
}

/**
 * MP077: pglz → lz4 TOAST compression (PG 14+).
 * Metadata only — values already stored keep their current compression.
 */
function fixMP077(text: string): string | null {
  if (!/\bpglz\b/i.test(text)) return null;
  return text.replace(/\bpglz\b/gi, 'lz4');
}

/**
 * MP074: ADD CONSTRAINT ... FOREIGN KEY → ... DEFERRABLE INITIALLY IMMEDIATE
 *
 * `INITIALLY IMMEDIATE` — not `INITIALLY DEFERRED` — because it keeps the
 * check happening at the end of each statement exactly as before, while
 * letting a bulk load opt in with `SET CONSTRAINTS ... DEFERRED`. Flipping the
 * default to DEFERRED would move every FK error to COMMIT time, which is a
 * behaviour change the fixer will not make on its own.
 *
 * Only the ALTER TABLE form is rewritten; an inline FK inside CREATE TABLE
 * needs the clause attached to one specific column definition, which is left
 * to the author.
 */
function fixMP074(text: string): string | null {
  if (/\bdeferrable\b/i.test(text)) return null;
  if (!/ALTER\s+TABLE/i.test(text)) return null;
  if (!/ADD\s+CONSTRAINT/i.test(text) || !/FOREIGN\s+KEY/i.test(text)) return null;
  return appendClause(text, 'DEFERRABLE INITIALLY IMMEDIATE', true);
}

/**
 * MP038: INT → BIGINT on primary/foreign key columns in CREATE TABLE.
 *
 * Bounded to CREATE TABLE on purpose: the table has no rows yet, so widening
 * the type is free. The same edit on an existing column rewrites every row.
 */
function fixMP038(text: string): string | null {
  return rewriteColumnDefs(text, def => {
    if (!/\b(PRIMARY\s+KEY|REFERENCES)\b/i.test(def)) return null;
    const match = /^(\s*(?:"[^"]+"|[A-Za-z_][\w$]*)\s+)(integer|int4|int|smallint|int2)\b/i.exec(def);
    if (!match) return null;
    return def.slice(0, match[1]!.length) + 'BIGINT' + def.slice(match[0].length);
  });
}

/**
 * MP039: SERIAL → GENERATED BY DEFAULT AS IDENTITY in CREATE TABLE.
 *
 * `BY DEFAULT`, not `ALWAYS`: SERIAL lets you insert an explicit value and so
 * does BY DEFAULT, while ALWAYS rejects it. The identity sequence keeps the
 * same `table_column_seq` name SERIAL would have produced, so setval() calls
 * elsewhere keep working.
 */
function fixMP039(text: string): string | null {
  const widths: Record<string, string> = {
    smallserial: 'SMALLINT', serial2: 'SMALLINT',
    serial: 'INTEGER', serial4: 'INTEGER',
    bigserial: 'BIGINT', serial8: 'BIGINT',
  };
  return rewriteColumnDefs(text, def => {
    const match = /^(\s*(?:"[^"]+"|[A-Za-z_][\w$]*)\s+)(smallserial|serial2|serial4|serial8|bigserial|serial)\b/i.exec(def);
    if (!match) return null;
    const width = widths[match[2]!.toLowerCase()];
    if (!width) return null;
    return def.slice(0, match[1]!.length) + `${width} GENERATED BY DEFAULT AS IDENTITY` + def.slice(match[0].length);
  });
}

/**
 * MP042: give an unnamed index the name PostgreSQL would have generated.
 *
 * `CREATE INDEX ON users (email)` becomes `CREATE INDEX users_email_idx ...`,
 * which is byte-for-byte the name PostgreSQL picks itself — so this makes the
 * name referenceable without changing anything about the resulting index.
 * Expression indexes are skipped: PostgreSQL names those `<table>_expr_idx`
 * with a collision counter we cannot reproduce from the file alone.
 */
function fixMP042(text: string): string | null {
  const head = /(CREATE\s+(?:UNIQUE\s+)?INDEX\s+(?:CONCURRENTLY\s+)?(?:IF\s+NOT\s+EXISTS\s+)?)ON\s+([A-Za-z_][\w$]*(?:\.[A-Za-z_][\w$]*)?)\s*(USING\s+[A-Za-z_][\w$]*\s*)?\(([^()]*)\)/i;
  const match = head.exec(text);
  if (!match) return null;

  const table = match[2]!.split('.').pop()!;
  const columns = match[4]!.split(',').map(c => c.trim());
  const names: string[] = [];
  for (const column of columns) {
    const plain = /^([A-Za-z_][\w$]*)(?:\s+(?:ASC|DESC))?(?:\s+NULLS\s+(?:FIRST|LAST))?$/i.exec(column);
    if (!plain) return null;
    names.push(plain[1]!.toLowerCase());
  }
  if (names.length === 0) return null;

  const indexName = `${table.toLowerCase()}_${names.join('_')}_idx`;
  return text.slice(0, match.index) + match[1] + indexName + ' ' + text.slice(match.index + match[1]!.length);
}

/**
 * Apply `rewrite` to each top-level column definition of a CREATE TABLE.
 * Returns null when the statement is not a CREATE TABLE or nothing changed.
 */
function rewriteColumnDefs(text: string, rewrite: (def: string) => string | null): string | null {
  if (!/^\s*CREATE\s+(?:GLOBAL\s+|LOCAL\s+)?(?:TEMP(?:ORARY)?\s+|UNLOGGED\s+)?TABLE\b/i.test(text)) return null;

  const open = text.indexOf('(');
  if (open === -1) return null;
  const close = matchingParen(text, open);
  if (close === -1) return null;

  const body = text.slice(open + 1, close);
  const parts = splitTopLevel(body);
  let changed = false;
  const rewritten = parts.map(part => {
    const next = rewrite(part);
    if (next === null) return part;
    changed = true;
    return next;
  });
  if (!changed) return null;

  return text.slice(0, open + 1) + rewritten.join(',') + text.slice(close);
}

/** Index of the `)` matching the `(` at `open`, or -1. */
function matchingParen(text: string, open: number): number {
  let depth = 0;
  for (let i = open; i < text.length; i++) {
    const ch = text[i];
    if (ch === "'" || ch === '"') {
      i = skipLiteral(text, i, ch);
      continue;
    }
    if (ch === '(') depth++;
    else if (ch === ')') {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

/** Split a parenthesised list on commas that are not nested or quoted. */
function splitTopLevel(body: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let start = 0;
  for (let i = 0; i < body.length; i++) {
    const ch = body[i];
    if (ch === "'" || ch === '"') {
      i = skipLiteral(body, i, ch);
      continue;
    }
    if (ch === '(') depth++;
    else if (ch === ')') depth--;
    else if (ch === ',' && depth === 0) {
      parts.push(body.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(body.slice(start));
  return parts;
}

/** Index of the closing quote of the literal starting at `i`. */
function skipLiteral(text: string, i: number, quote: string): number {
  for (let j = i + 1; j < text.length; j++) {
    if (text[j] !== quote) continue;
    if (text[j + 1] === quote) { j++; continue; }
    return j;
  }
  return text.length;
}
