/**
 * Liquibase adapter — Tier 1 for formatted SQL, recipe for XML/YAML/JSON.
 *
 * A Liquibase changelog written in formatted SQL (`--liquibase formatted sql`)
 * is real SQL on disk: MigrationPilot reads it directly, and the `--changeset`
 * and `--rollback` annotations are comments, so the rollback half is ignored by
 * construction.
 *
 * XML, YAML and JSON changelogs are a different story. They describe changes
 * abstractly (`<addColumn>`, `<createIndex>`), and the SQL only exists once
 * Liquibase renders it for a specific database. MigrationPilot does not guess
 * at that rendering — it says so and gives you the command that produces it.
 */

import { join } from 'node:path';
import type { Adapter, AdapterResult, FrameworkRecipe, ResolvedMigration, SkippedFile } from './types.js';
import { exists, isDirectory, labelFor, listFiles, readText, toPosix, walkFiles } from './util.js';
import { isLiquibaseFormattedSql, liquibaseChangesets } from './sections.js';

const SEARCH_DIRS = [
  '.',
  'db/changelog',
  'db',
  'changelog',
  'changelogs',
  'migrations',
  'src/main/resources',
  'src/main/resources/db/changelog',
];

const STRUCTURED_EXTENSIONS = ['.xml', '.yaml', '.yml', '.json'];

export const liquibaseAdapter: Adapter = {
  id: 'liquibase',
  name: 'Liquibase',
  support: 'full',
  async resolve(root: string): Promise<AdapterResult | null> {
    const properties = await readText(join(root, 'liquibase.properties'));
    const configuredChangelog = properties?.match(/^\s*(?:liquibase\.command\.)?changeLogFile\s*[:=]\s*(.+)$/mi)?.[1]?.trim();

    // Cheap exit before any recursive scanning: no Liquibase evidence, no work.
    if (properties === null && !(await hasChangelogEvidence(root))) return null;

    const dirs = await searchDirs(root, configuredChangelog);
    const notes: string[] = [];
    const skipped: SkippedFile[] = [];
    const migrations: ResolvedMigration[] = [];
    const structured: string[] = [];
    const seen = new Set<string>();

    for (const dir of dirs) {
      // The project root is only scanned shallowly; dedicated changelog
      // directories are worth a deeper walk.
      const depth = dir === root ? 0 : 4;
      for (const file of await walkFiles(dir, depth)) {
        if (seen.has(file)) continue;
        seen.add(file);

        if (STRUCTURED_EXTENSIONS.some(ext => file.toLowerCase().endsWith(ext))) {
          if (/changelog|changeset/i.test(file) || file === configuredChangelogPath(root, configuredChangelog)) {
            structured.push(file);
          }
          continue;
        }
        if (!file.toLowerCase().endsWith('.sql')) continue;

        const sql = await readText(file);
        if (sql === null || !isLiquibaseFormattedSql(sql)) continue;

        const changesets = liquibaseChangesets(sql);
        migrations.push({
          path: file,
          label: labelFor(root, file),
          sql,
          version: labelFor(root, file),
          origin: 'sql-file',
          notes: changesets.length > 0 ? [`${changesets.length} changeset(s): ${changesets.join(', ')}`] : [],
        });
      }
    }

    for (const file of structured) {
      skipped.push({
        path: file,
        label: labelFor(root, file),
        reason: 'XML/YAML/JSON changelog — the SQL is generated by Liquibase at runtime and cannot be read from the file',
      });
    }

    const hasLiquibase = migrations.length > 0 || structured.length > 0 || properties !== null;
    if (!hasLiquibase) return null;

    migrations.sort((a, b) => a.label.localeCompare(b.label));

    if (migrations.length > 0) {
      notes.push('Only files starting with `--liquibase formatted sql` are read; `--rollback` lines are comments and are ignored.');
    }
    if (structured.length > 0) {
      notes.push(`${structured.length} XML/YAML/JSON changelog(s) found. Render them with \`liquibase updateSQL\` and pass the result via --from-command.`);
    }

    const recipe: FrameworkRecipe = {
      summary: 'XML, YAML and JSON changelogs describe changes abstractly; Liquibase renders the SQL for your target database.',
      steps: [
        'Render the changelog to SQL without applying it:',
        '  liquibase updateSQL --changelog-file=<changelog> --url=<jdbc-url> > pending.sql',
        'Then analyze the rendered SQL:',
        '  migrationpilot analyze pending.sql',
        'The output also contains Liquibase\'s own DATABASECHANGELOG bookkeeping statements — those are expected.',
      ],
      fromCommand: 'migrationpilot check --from-command "liquibase updateSQL --changelog-file=<changelog> --url=<jdbc-url>"',
    };

    // Report the directories the changelogs actually live in, not every
    // directory that was searched.
    const found = [...migrations.map(m => m.label), ...skipped.map(s => s.label)];
    const sources = [...new Set(found.map(label => label.split('/').slice(0, -1).join('/') || '.'))].sort();

    return {
      id: 'liquibase',
      name: 'Liquibase',
      support: migrations.length > 0 ? 'full' : 'recipe',
      root,
      sources: sources.length > 0 ? sources : dirs.map(d => toPosix(labelFor(root, d))),
      ordering: 'file path order (matches Liquibase\'s `includeAll` default); a master changelog can override this',
      migrations,
      skipped,
      notes,
      recipe: structured.length > 0 || migrations.length === 0 ? recipe : undefined,
    };
  },
};

function configuredChangelogPath(root: string, configured?: string): string | undefined {
  return configured ? join(root, configured) : undefined;
}

/** Is there any sign of Liquibase here, without walking the whole project? */
async function hasChangelogEvidence(root: string): Promise<boolean> {
  for (const dir of ['db/changelog', 'src/main/resources/db/changelog', 'changelog', 'changelogs']) {
    if (await isDirectory(join(root, dir))) return true;
  }
  for (const dir of ['.', 'db', 'migrations', 'src/main/resources']) {
    const files = await listFiles(join(root, dir));
    if (files.some(f => /changelog/i.test(f))) return true;
    for (const file of files.filter(f => f.toLowerCase().endsWith('.sql'))) {
      const sql = await readText(join(root, dir, file));
      if (sql && isLiquibaseFormattedSql(sql)) return true;
    }
  }
  return false;
}

async function searchDirs(root: string, configuredChangelog?: string): Promise<string[]> {
  const dirs: string[] = [];

  if (configuredChangelog) {
    const full = join(root, configuredChangelog);
    const dir = (await isDirectory(full)) ? full : join(full, '..');
    if (await exists(dir)) dirs.push(dir);
  }

  for (const candidate of SEARCH_DIRS) {
    const dir = join(root, candidate);
    if (await isDirectory(dir) && !dirs.includes(dir)) dirs.push(dir);
  }

  return dirs;
}
