/**
 * Django / Alembic / Rails adapters — Tier 2 (recipe).
 *
 * These frameworks describe migrations in Python or Ruby. The SQL exists only
 * once the framework renders it against a specific database, so MigrationPilot
 * does not pretend to read it. Each adapter reports what it found, explains
 * exactly why there is nothing to analyze yet, and hands back the command that
 * produces the SQL — which `check --from-command` can run and analyze for real.
 */

import { join } from 'node:path';
import type { Adapter, AdapterResult, SkippedFile } from './types.js';
import { exists, isDirectory, labelFor, listDirs, listFiles, readText, toPosix } from './util.js';

export const djangoAdapter: Adapter = {
  id: 'django',
  name: 'Django',
  support: 'recipe',
  async resolve(root: string): Promise<AdapterResult | null> {
    if (!(await exists(join(root, 'manage.py')))) return null;

    const skipped: SkippedFile[] = [];
    const sources: string[] = [];
    const appDirs = [...(await listDirs(root)), ...(await listDirs(join(root, 'src'))).map(d => join('src', d))];

    for (const app of appDirs) {
      const dir = join(root, app, 'migrations');
      if (!(await isDirectory(dir))) continue;
      const files = (await listFiles(dir)).filter(f => f.endsWith('.py') && f !== '__init__.py');
      if (files.length === 0) continue;
      sources.push(toPosix(labelFor(root, dir)));
      for (const file of files) {
        const path = join(dir, file);
        skipped.push({
          path,
          label: labelFor(root, path),
          reason: 'Python migration — the SQL is generated by `manage.py sqlmigrate`',
        });
      }
    }

    if (sources.length === 0) return null;

    const appLabel = sources[0]?.split('/').slice(-2)[0] ?? '<app>';

    return {
      id: 'django',
      name: 'Django',
      support: 'recipe',
      root,
      sources,
      ordering: 'Django resolves order from each migration\'s `dependencies` list, not from filenames',
      migrations: [],
      skipped,
      notes: [
        `${skipped.length} Python migration(s) found. Django renders their SQL at apply time.`,
      ],
      recipe: {
        summary: '`manage.py sqlmigrate` prints the exact SQL for one migration. It needs a database connection to resolve constraint names, so run it against a copy of the database you will apply to.',
        steps: [
          `python manage.py sqlmigrate ${appLabel} 0001_initial`,
          'Analyze it directly:',
          `  migrationpilot check --from-command "python manage.py sqlmigrate ${appLabel} 0001_initial"`,
          'Or capture the SQL first:',
          `  python manage.py sqlmigrate ${appLabel} 0001_initial > migration.sql && migrationpilot analyze migration.sql`,
          'Use `python manage.py showmigrations` to list the unapplied migrations you want to check.',
        ],
        fromCommand: `migrationpilot check --from-command "python manage.py sqlmigrate ${appLabel} 0001_initial"`,
      },
    };
  },
};

export const alembicAdapter: Adapter = {
  id: 'alembic',
  name: 'Alembic (SQLAlchemy)',
  support: 'recipe',
  async resolve(root: string): Promise<AdapterResult | null> {
    const ini = await readText(join(root, 'alembic.ini'));
    const scriptLocation = ini?.match(/^\s*script_location\s*=\s*(.+)$/mi)?.[1]?.trim();

    const candidates = [
      ...(scriptLocation ? [join(scriptLocation, 'versions')] : []),
      'alembic/versions',
      'migrations/versions',
      'db/migrations/versions',
    ];

    let versionsDir: string | null = null;
    for (const candidate of candidates) {
      const dir = join(root, candidate);
      if (await isDirectory(dir)) { versionsDir = dir; break; }
    }
    if (!versionsDir) return null;

    const files = (await listFiles(versionsDir)).filter(f => f.endsWith('.py') && f !== '__init__.py');
    if (files.length === 0 && ini === null) return null;

    const skipped: SkippedFile[] = files.map(file => ({
      path: join(versionsDir!, file),
      label: labelFor(root, join(versionsDir!, file)),
      reason: 'Python migration — the SQL is generated by Alembic in offline (--sql) mode',
    }));

    return {
      id: 'alembic',
      name: 'Alembic (SQLAlchemy)',
      support: 'recipe',
      root,
      sources: [toPosix(labelFor(root, versionsDir))],
      ordering: 'Alembic resolves order from the revision/down_revision chain, not from filenames',
      migrations: [],
      skipped,
      notes: [
        `${skipped.length} revision script(s) found. Alembic renders their SQL at apply time.`,
      ],
      recipe: {
        summary: 'Alembic\'s offline mode (`--sql`) prints the migration SQL instead of executing it.',
        steps: [
          'alembic upgrade head --sql',
          'Offline mode starts from base by default, so that emits the whole history. For just what is pending, name the range:',
          '  alembic upgrade <current_revision>:head --sql',
          'Analyze it directly:',
          '  migrationpilot check --from-command "alembic upgrade <current_revision>:head --sql"',
          'Alembic writes SQL to stdout and its logging to stderr, so the pipe stays clean.',
        ],
        fromCommand: 'migrationpilot check --from-command "alembic upgrade head --sql"',
      },
    };
  },
};

/** `add_index_to_users` → `AddIndexToUsers` (Rails migration class naming). */
function camelize(snake: string): string {
  return snake.split('_').filter(Boolean).map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

export const railsAdapter: Adapter = {
  id: 'rails',
  name: 'Rails ActiveRecord',
  support: 'recipe',
  async resolve(root: string): Promise<AdapterResult | null> {
    const migrateDir = join(root, 'db', 'migrate');
    if (!(await isDirectory(migrateDir))) return null;
    if (!(await exists(join(root, 'Gemfile'))) && !(await exists(join(root, 'config', 'application.rb')))) return null;

    const files = (await listFiles(migrateDir)).filter(f => f.endsWith('.rb'));
    const skipped: SkippedFile[] = files.map(file => ({
      path: join(migrateDir, file),
      label: labelFor(root, join(migrateDir, file)),
      reason: 'Ruby migration — ActiveRecord generates the SQL for your adapter at apply time',
    }));

    const notes = [`${skipped.length} Ruby migration(s) found. ActiveRecord renders their SQL at apply time.`];

    const structurePath = join(root, 'db', 'structure.sql');
    if (await exists(structurePath)) {
      notes.push(
        'db/structure.sql exists, but it is a schema dump of the whole database, not the change you are about to ship. ' +
        '`migrationpilot analyze db/structure.sql` will report on every table in it, which is rarely what you want in CI.',
      );
    }

    const example = files[files.length - 1]?.replace(/\.rb$/, '') ?? '20240101000000_add_index';
    const className = camelize(example.replace(/^\d+_/, ''));

    return {
      id: 'rails',
      name: 'Rails ActiveRecord',
      support: 'recipe',
      root,
      sources: [toPosix(labelFor(root, migrateDir))],
      ordering: 'timestamp prefix of the filename — the order ActiveRecord runs migrations in',
      migrations: [],
      skipped,
      notes,
      recipe: {
        summary: 'Rails has no built-in "print the SQL for this migration" command, so the SQL has to be echoed from a scratch-database run.',
        steps: [
          'Print the DDL instead of executing it (use a development or throwaway database):',
          '  bin/rails runner \'',
          '    ActiveRecord::Base.connection.singleton_class.prepend(Module.new do',
          '      def execute(sql, name = nil); puts sql; end',
          '    end)',
          `    require Rails.root.join("db/migrate/${example}").to_s`,
          `    ${className}.new.migrate(:up)`,
          '  \'',
          'Pipe that straight in with `migrationpilot check --from-command "bin/rails runner \'...\'"`.',
          'Caveat: this only catches DDL that goes through `execute`; anything the adapter runs by another path will not print.',
          'Set `config.active_record.schema_format = :sql` if you also want db/structure.sql tracked in review.',
        ],
      },
    };
  },
};
